apiVersion: ENC[AES256_GCM,data:CKw=,iv:w+s24ylVMyFr2rrXYuxp7PMj+Oi7Wi/KPQNBKL+vh/k=,tag:h28hmJ4djnRjmJV9ltx3cQ==,type:str]
kind: ENC[AES256_GCM,data:OVoX4l3X,iv:LZEVmFnmYi3UlFMA8TQ2JsKPNyAxj0prJR1ftCyxy+8=,tag:3TtyuCapgnye/NiBCDgl+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XuZtXDe83KlKqEqByQ==,iv:KOWsjq740HK32B/n7UpJIF/Jjvdofw2Dzh+UDb841Xg=,tag:ae4HeSc7Ew7kBWBpZWmhKA==,type:str]
    namespace: ENC[AES256_GCM,data:JH5GjXsKK5TVqw==,iv:+81OrbP+nqFlkzkByBhWwJ1/JdXL1pzW5v8Vs+AZ2L0=,tag:lWlbxSbwcmVxZAYQ4xT5OQ==,type:str]
type: ENC[AES256_GCM,data:PZw6HHNk,iv:Pxd3ZxK6mmUioJKKIRXc5Bn2tF0n6zmEoFgkJABJs5E=,tag:4I0ETYFY2w4anbmtTFCM/A==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:EOC8C00=,iv:tI6aUd49+rHqjeqIUNSIyVfgloXfEdsYYWUS8OgC5bk=,tag:pr8+jiDNPFGhScdbjGQrbw==,type:str]
    admin-password: ENC[AES256_GCM,data:BG8JzSMvdLKnRYrSkarVQH3gUQgERXdm,iv:ogJAci+B5lz6f/cVXIgUL6cJwasxORHaQWdT7GUXxek=,tag:F2arhhruu5a8aICA/IB5Fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOHF6VlNDTytOeW9mcHpT
            ai83eWc2Q1FFUnV2ZWM4Sm5XZzhhUVllWGlZClhiSXUzN3B2UzdJV2ptVHVGcW95
            aXVCRGxmaEUyb0s0L25SdGx1cytIVG8KLS0tIGZyYmRFMjVOTjRqMklqRHpIcVIz
            aGNzdUJ3ZjEydEhkdWxiTU1VRG5BV3cKqfKBm/MyKPscb29Yi6kT9qY1DKiJxTVO
            FjrN7DsvPBPCewUhPOFfSFT0KG0ZX5SGdUIA/wNPB0D1sR/LqL9Tcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-07-10T10:48:44Z"
    mac: ENC[AES256_GCM,data:fp6ow4oumzR2qCXEhReFJEG4lg4X0i1ILJK8fYbvgmN1XpvAtaZzd3huhWE0kU8nb+IzFdv177fjgHN+d2nWHJQYxySka/XfHF38NmpjLvvUBLWPU9eEAxiRiRzGnqqoiPs3mK4hfNAuiOVXhd9lpf6M3LbCMHY+SthusD3RWqo=,iv:Dt/C9SZH7RQ6YUZMvJ4I2liJrySpqNq5rxERxPGbqhc=,tag:n5YS+3urGQha3Fvp5zkQYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
