apiVersion: ENC[AES256_GCM,data:y0I=,iv:LN5KsJ2iEAjMp+zS1SyCEhyiE8jOvKLJhcQkHynjX4Q=,tag:34oI5E3cI+QpI6EgM5oeyg==,type:str]
kind: ENC[AES256_GCM,data:0Xk5GHpE,iv:AVSpvINGA1UIF6l3S1+MLDeZlBJNrwT72XnhYQcvekE=,tag:f3Lj5RdqJpM7PXeYMGSCkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H7Maupr7dyedWg6rwg==,iv:g7a8AV9IIrWCRlimQ10VhzFH+RLFrHr9l0Q6kBVtuKo=,tag:KJQkrgXkpN1bzKv4iV0dlg==,type:str]
    namespace: ENC[AES256_GCM,data:i5QC/fIXO+R5ww==,iv:MdcvX7ZXuPiB+ID1+U0Vd0L3c1jegXbTnV3H9/7ahCI=,tag:/+yKUut9E/j2jQyQ4r7I6A==,type:str]
type: ENC[AES256_GCM,data:MW2Uqgvv,iv:1Re0k6YIpaHEb49KtPB9DPCBDU0MeH5ozfE9+qiwdfw=,tag:CYQvld81IEoJVFmRJ0RWhw==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:UUyYL6s=,iv:QpG4MCpFGarvWgEo7ytcU6Wxoon5FtURR8E4GnT4VtI=,tag:+ffqrWIL+8K6aquc3PJEWg==,type:str]
    admin-password: ENC[AES256_GCM,data:U/yW0ZySuJ5B+8XgjbEHQOjzttA+nLLo,iv:iXasRKY3ERE86BCwj2+ejWYxwXPDhrgGxEnEZ64vtp4=,tag:HIbyPrT3oW8mfbJcFDw+mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYWt5Vys5TXJpOUJUNmZ0
            WkhxM2lleWtIT0ExTG1sUmRKSHN5MldmMW0wCnhtTHkybmU4eWpXakdKc1kwVWlH
            TEFrZUYvRmh1cjlYaG8xSGhod21MdWcKLS0tIHpFZHBiTzJZbFpza3RwVFpMSVh4
            dXg4N2E5MFNOeGtzc2E1cFF0K3QzUUEKhFHDWZ3LZCtaEvP+YUT8Jdjm/o9nTSxd
            NB83Mr9zUF/VOjLE3dsd9GvL9Gbhz7Kz3bq7jyB0jdPGsN1LXrp9dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-08-29T12:02:43Z"
    mac: ENC[AES256_GCM,data:QChAsaXfYpSaLTy2CfvSixwWcpfh6fGns9Z63jankdFTNuEjbdmuohMz10EzfWeTQ4zeN0WiiVMQHwyGixPwAlU7b4duVx0ngHzEGhsQqYF5sP9nRWwMoJrfMLAvq7Bes1XgmcrpLrYsoEGMxy4/B5jK1dmHUcsFaxst2uq3cxs=,iv:tM6EKSZGNUNBy2HHweHZFIMHZh1oPhkF65yC0slUAIY=,tag:+k6Sfb6dv4cGyTnEimWwlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:/Ok=,iv:4QeQ+ZpiSTBVcSo5VcC1A//PJeU1cuYVilxWedUlZhU=,tag:jVGXVVZ/IU79I/RxEJA6+w==,type:str]
kind: ENC[AES256_GCM,data:Q37SqooW,iv:cgnNqveOnSoQc/LQWy+N6ewiexxvZlVlqPwE08n5xiw=,tag:pm0IwBDJ1n36iY4p3BBW9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B9hGbFycxk5O+kgH63YJESMRaSQ=,iv:9Neg8p4Ila+LccFabsCUOAZlWN+Q+PDufAgdOKLcMKs=,tag:AOOzuzIUkcZ68bWvPDUGyw==,type:str]
    namespace: ENC[AES256_GCM,data:GOMrx8fORvWrJQ==,iv:/KLvZDgId+btBiaJKH+f0cCGbd8XBCHqk2OyeAcVwog=,tag:T5sWKjRDTLUH/e+KBaniiw==,type:str]
type: ENC[AES256_GCM,data:XKvOUUVo,iv:iPajg8wZqxYNcztWrfZIOno+xSWPro+sudKMnZYlJbA=,tag:Ph3BYKOnmFLhhifD3YxfSA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:rvSqHfvMYEWXTg0pq/E2H569U/k=,iv:AxVa4dnsky92skGPDwsF7JJZnJfCrIrQnJQlHGo4JKA=,tag:ZEOoqZCDn2EeGVbUNpbPGQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:2CzX7tfi/iZa4u1DK6dLaaFaLoQ1Jd6WeGlPYEAmI19yaX1IlCCsbQ==,iv:cnIX5ZIEYk6mbE0Ou4iiBnAsrKNjrBG9GRtQXV66eig=,tag:mrZ5SKW7hH4InETWGYEf/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYWt5Vys5TXJpOUJUNmZ0
            WkhxM2lleWtIT0ExTG1sUmRKSHN5MldmMW0wCnhtTHkybmU4eWpXakdKc1kwVWlH
            TEFrZUYvRmh1cjlYaG8xSGhod21MdWcKLS0tIHpFZHBiTzJZbFpza3RwVFpMSVh4
            dXg4N2E5MFNOeGtzc2E1cFF0K3QzUUEKhFHDWZ3LZCtaEvP+YUT8Jdjm/o9nTSxd
            NB83Mr9zUF/VOjLE3dsd9GvL9Gbhz7Kz3bq7jyB0jdPGsN1LXrp9dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-08-29T12:02:43Z"
    mac: ENC[AES256_GCM,data:QChAsaXfYpSaLTy2CfvSixwWcpfh6fGns9Z63jankdFTNuEjbdmuohMz10EzfWeTQ4zeN0WiiVMQHwyGixPwAlU7b4duVx0ngHzEGhsQqYF5sP9nRWwMoJrfMLAvq7Bes1XgmcrpLrYsoEGMxy4/B5jK1dmHUcsFaxst2uq3cxs=,iv:tM6EKSZGNUNBy2HHweHZFIMHZh1oPhkF65yC0slUAIY=,tag:+k6Sfb6dv4cGyTnEimWwlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
