apiVersion: ENC[AES256_GCM,data:hCQ=,iv:pCfORcF9qHQVWwwnyE7fAEv4SZT13UzLw18PtoaYlaw=,tag:rS2GEYlxGoHJBrBMIfoAGQ==,type:str]
kind: ENC[AES256_GCM,data:0K6L7nXv,iv:0zrGeEIeSXas7zd2JIFtDJLSGF6+c17F6H8xwzfVeII=,tag:cx5BO6Ynpxb+zI1hOzF76w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:98D0z1Us8lT3IpbFCw==,iv:kOew/DURJBidad8w3tuvVITmuN9HC2TsqJLQZRcY1NA=,tag:HflD/bi5ucZ9xj7iATrRVg==,type:str]
    namespace: ENC[AES256_GCM,data:sYCPhvd/80dYiw==,iv:bahqEzxxzwvU1DlKRwepowEDE7V2hLfewfbkzIsHOkE=,tag:lQ9CFOTvPLvosCWO4mk9Tw==,type:str]
type: ENC[AES256_GCM,data:OR4ywhUW,iv:dUskoH2X4LpPVnx2SpeDAdFYb3tugXYEHIuy4jV9Efs=,tag:ZnDwpfc7jmxaHEzBROnZ7A==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:3iEFrYA=,iv:N6bV+NVWixq0PokCKy4VVxyjp27wtuTtjaCxGiX7KZQ=,tag:q1n+io7EBNDMGa0x5s0Prg==,type:str]
    admin-password: ENC[AES256_GCM,data:VicGW2bfR+n/jPQYV2dNZGYApJkDnsV6,iv:uPp678ul76KczwmworU34ND7sZZIudM+Pmi4h9xM7UQ=,tag:9jWWdgKwRBEhu99M08xsvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWjlDOXFoaGU1Vnd3M2Z6
            a3gvaVB5R1JDOGVUYzI3SFhXRnVEMHlhcWhVCk9pTmdJTnJBS0dibm81VGxFd3Ux
            aktrU2NUZDZNV3JTUlZXZStrdVlXT2MKLS0tIC9mV2pHM05pcys4MUxZZmpWaFcy
            VTB1SHlFbldZTWVjc1dqcWh5MjJSbFkKfQgDukrrkxpir2OVCJFbji89y1cmqTee
            nJEEw1rRXYNmHCBUg93osf1WjEwaadDR5DlTc9l+pAeDlJE8HW56KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-08-29T13:43:43Z"
    mac: ENC[AES256_GCM,data:GggaqgqrF73Qn/14XUTr8Cxp1vNEzLXq5uO8i630pMTs2boPvHU+bAEVyAWEVfxFJsnga6+D3rCXYTCmWwGNcqR7ok04Fv1gRUr3jNF7C1pP7GgvXd/vDwpulV4roNZwxaKpMVhmH8aHAT/jKyJ/9nop0/pOHSeycYQ+muCV3pU=,iv:xJ4Ow9yGPyvOR7i7+3uD99y8c+yd+VaLnXcKIp/Ss0E=,tag:FqXz4jI5i6cohcVzUQ7Fvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:fPs=,iv:n3j3IX6wxUosOrugDmUI+pj8EdD1EbgFE0S55JWyLOs=,tag:ZxHqEabEvpm5Kw7GZSqTyw==,type:str]
kind: ENC[AES256_GCM,data:a4JxTRxk,iv:1JObhaEaMDqqhRANdstJHVMQwshARbrksyqEXsAx8y4=,tag:XOtAakO8l+GBBEOf42R70w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ifcKiLVG1z9gDdfSnvLFgrNQYjs=,iv:nggJm8IpANnRhBACkL+5unKFXJ4IlQMBDGUGY+G8Im4=,tag:ll0aaThOY7iDxOQbKlAzcg==,type:str]
    namespace: ENC[AES256_GCM,data:KeF9XsRMfG/S0A==,iv:s+vQ9KcIEIeVz52YF1oELXFIp5snAB7T93FQRiNyuMs=,tag:7aRn7gCzAQyS7yk9qDGWPg==,type:str]
type: ENC[AES256_GCM,data:FZl3G6JZ,iv:p9FosM3xe65uAgcrbfIT8/u2sb13HHGhJ8i0AcfXe3s=,tag:rbJKGFaiyv3T6K5a9LoAAw==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:B5NOFJHDZ0bE7nnyAUwTEWcOSf8=,iv:ge4M8uG5vPGHheUnzK2FIWUwjJVBVr+oFe7LA8EgVWg=,tag:5HD2DDwTdJBwzww6WibLvQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:JwD/SmKCxfn61beiJHgXXRCw4tjOSB/TKgvk/DHQ0N4VqdcgBwDBNg==,iv:fKGge4HQdg6wzId+3T6WrCE4+kPKI9vnTBRSTIvGo+8=,tag:w3uo3TA6xhxMh+CceJX8dQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWjlDOXFoaGU1Vnd3M2Z6
            a3gvaVB5R1JDOGVUYzI3SFhXRnVEMHlhcWhVCk9pTmdJTnJBS0dibm81VGxFd3Ux
            aktrU2NUZDZNV3JTUlZXZStrdVlXT2MKLS0tIC9mV2pHM05pcys4MUxZZmpWaFcy
            VTB1SHlFbldZTWVjc1dqcWh5MjJSbFkKfQgDukrrkxpir2OVCJFbji89y1cmqTee
            nJEEw1rRXYNmHCBUg93osf1WjEwaadDR5DlTc9l+pAeDlJE8HW56KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-08-29T13:43:43Z"
    mac: ENC[AES256_GCM,data:GggaqgqrF73Qn/14XUTr8Cxp1vNEzLXq5uO8i630pMTs2boPvHU+bAEVyAWEVfxFJsnga6+D3rCXYTCmWwGNcqR7ok04Fv1gRUr3jNF7C1pP7GgvXd/vDwpulV4roNZwxaKpMVhmH8aHAT/jKyJ/9nop0/pOHSeycYQ+muCV3pU=,iv:xJ4Ow9yGPyvOR7i7+3uD99y8c+yd+VaLnXcKIp/Ss0E=,tag:FqXz4jI5i6cohcVzUQ7Fvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
