#ENC[AES256_GCM,data:oOBAxUpoeh2Qbr/DTTa6T1W81Si3y56x/JAgJI8rH4llaIN6fxfyOp6JAzFpz5eCiK3Sc9nZbeIIEcRmjeRlFeax,iv:7Y9iqWr9bdNm3vDSujKjLETXCsFMnd/6p4bwtOBsGRg=,tag:jeQJbIujf5Y73Hkde3CV0g==,type:comment]
#
#ENC[AES256_GCM,data:uwBlBt2n2xMNYr7sS6hg+yj/OwXrQtSkwQhaQUnEMdaJHtIqiP+NN7yF56VZSAR/,iv:rbgAGnZjx1jXYG4tKknSb8mNBabQYP7kS8qRM7KAlms=,tag:WtAd3T2TwRA5kzt1GI0Bsw==,type:comment]
#ENC[AES256_GCM,data:3UzOMbZmH1nWyIQ2wwCtjwwS7MrZkgrm0o3D+r04LlAR5VtpicVXRmcCDuWA,iv:3Wn51FMH6zFMxZP+5UQ+FgT55LOVpn3FgMhvFDCUu2g=,tag:3wMFsI35p1BH/IIL9d2+CQ==,type:comment]
#ENC[AES256_GCM,data:YvYP641wx/OLlTAfJS+OGOX7dNuEsR2GgXjwBoD8mbVtWeRzaB7NYD0pjbObNuE2iQOSuXoZtzkzTlFJcg==,iv:p8JfhzT5l3yZhVjwl0SuCs4nSxlj12rqz0j6Dv6DAoA=,tag:JW+1FuI3sR5QYt5ApNnRGA==,type:comment]
#ENC[AES256_GCM,data:cxc8NO/3WATHAUuVh1yC7RK7iuld9ceT+OO0haMCbnMKI7SZNzei68o/KYvGgCJ19DLVukIo2dIrvFjjIXg=,iv:S72kaQucslWt5AvyrvAZEgfubyd8iA2CJH4fkswqnu0=,tag:JYq4vk4VlYB/WGKV6ovMOQ==,type:comment]
#ENC[AES256_GCM,data:4AigmOkmPXtHem4ua3XKcAqseMdU6hQIuiRblx8X17n/qISCCbIa0gX7wSlj/+VrtugXfw5CM1pd2sw1XwDssJkl7VMRHQTNIndqRocIkCPMYU9NYchr7uxMZa4aZ2xRSZJcqw==,iv:KWgStcN6ONbcy/mPZVBWFnF4DwNwa2F1zVe/w0tFgWk=,tag:ozi58Z4HtPc/awrmPfMU9A==,type:comment]
#ENC[AES256_GCM,data:VjMLQnFK/Pe3ZF3ctg==,iv:Uo7AlYSxCZmoRAFiy++Vzpitiko12uwe1StkI3xYvK0=,tag:H5njqsPWY5pdb7yM5gn0oQ==,type:comment]
#ENC[AES256_GCM,data:GQAVhbgyICr46bsXZBIKhwA32mT2hjxbpFbTthE96Ipd+a+Hx+Vwo2osHBcqfpPD4649IyxFYc1CHHflBMCCSflbGfn/hYXVDMqtJrOLKl5VF/sCQPzR6Gow/S5lhcnRO6UifVpoclfqULvmiWcmlKvUZg==,iv:ecTv6ePgNpZptq+9WtKdkl4SRsuV45o81Yt+xjZxGq4=,tag:c5XcfW5/P1kws24nWbBAAw==,type:comment]
apiVersion: ENC[AES256_GCM,data:9VI=,iv:VXWHfbpjDwB0H4QrWiSZAwRQy1j1oXEA9lWoHhVhx8w=,tag:ue/RTx0c8lcJgmvaXi4bYA==,type:str]
kind: ENC[AES256_GCM,data:6NpWf7zX,iv:Iusczvsyu1RQs5nAOWPV6Xwukqw0r8bCPOI+nk92L0A=,tag:ELCoHXsK295b9SqmdowewQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RRb/hichp8pPyXoAwp3GVawlqQ41BWChholr0ao5tw==,iv:crlchn66yPC49XojpAN1S+8eLG3G06QvaV0FLQBVxW8=,tag:zoDkD9+jG3CoBc1D6OWhnA==,type:str]
    namespace: ENC[AES256_GCM,data:Uy1HaXwXVHFZPo/ikyBo,iv:+vDfD1nMUMMFduHtKd84+n58J4vlCn54osdxS9gXUww=,tag:Vh5OeNVgmuvhdw10bVSuLw==,type:str]
type: ENC[AES256_GCM,data:g5pjHDFT,iv:w0AbtQWRjjyP/TGKHCexdtJcSR5ZJRPyP9cEi4k+wMc=,tag:hTC6OM0n2ZPtgRdAT6QPtA==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:HfCOcx4lUQBMUzjnRz7aS/8IsaXjF7TXnLfKBnwt2jQXQbc=,iv:CzZ5FA4nbs7FnSnZqtjdLIsX+eJjGoosVoC7E/ZBeS0=,tag:ayTqbqrZ6suC0v4XOgjsPw==,type:str]
    client-secret: ENC[AES256_GCM,data:GcFjfOehB7CJpyxOPuw3AQ+A8E4SAeO7QW3wb+tyfAPZLik=,iv:sugyg8attywpsgUIjm0BYvggySYVesldD520corx/zY=,tag:YD3tbOEFXPeTG42IjV7DUw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:pU00HP6rO4ovdyMSF0taBz+7XgwzLP9rGvaYnhLPtsWTnyP0jOukC6hjOf4=,iv:IGJKKASKTXdYOPf56iUQ7SxJOXtGriR5ATM5m6COcyc=,tag:ZoAEXz6XWeFuKBcpDTvW4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d2hYdE44TmduR2lrdUc0
            VzJPUXhZQ1VxSVlhTEFVaUZvRVhYK0JweFEwCm9tYmp5dkJrNEc0YnJ0cDh5enZX
            eEpUbGJpaEU5TW1UQ3ZZQ1J4T3NmdncKLS0tIHRySHhTenh2VmpNTWVNR2IwOGNO
            cGljUlBXZHBNN2hOd2FBM3JtQ2pZT3MKSsk5IuBb7+NuRzbcJu3saWme/x6DhmyQ
            8ruE6np8LiD+Pua9Fn+xJL9vsqOPsn9S/yygxcL46/V7aFpGKfVRYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-09-14T17:52:07Z"
    mac: ENC[AES256_GCM,data:XUjGyUn3b+bpqvWlaA6nTjNoPNQULwRvw1UGrz31p5QbRuvEWKGGjVT2IfXMfntNJe4Y5rYJanIJMvWVtBJ0qOrI/xB4c4nohiIpmYYvsbMJHsvv8xMnfIPSMaOedFR5YN1PyWdhCw5wORB/5Zp/wpDG8dNdlR851HJRhhG5jJ4=,iv:owHNpzi+0qVJoSvlclxEx3ZQJ991CJk2531VEAgEXSE=,tag:aSHwdyenUbfUeYqCrUW/eA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
