apiVersion: ENC[AES256_GCM,data:BzA=,iv:Oc09Ww/q/sZMi94r/U7RvtSfedONcf0wzY3c+zctnIU=,tag:jA4Vb1gfrobynCKaPaWxlQ==,type:str]
kind: ENC[AES256_GCM,data:0FC/XAZ/,iv:bGzJRaZOx4KKUE1mlOE61MQ+nlZDyc5JywlJbyFhd7s=,tag:SJJbh1raLh6cLQ/EIIaYxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u+ziutNLlDMMuFE4pLwS9PbaUrwlH3g9KayygA==,iv:OKtcp3g6lIAUB42rPJq77REgr/WCcGyAWUgBI3Hjq+E=,tag:KD/DXzu2jW5iJRIwdsDl2A==,type:str]
    namespace: ENC[AES256_GCM,data:dAC9SUpuFs0doGOYibEr,iv:EocYwlZ3MC5TVlLGgjmr4C1Oc/WqxgJMmXuLYE15FOw=,tag:rXzw60nI/yGec+5z2a8bGg==,type:str]
type: ENC[AES256_GCM,data:7943kmmx,iv:NPdunZ78+VMcYauMlqtgOmCgBlPtb5yUjgm1R2SqmSI=,tag:brybY5B6SMzuAMWbJ6l8zg==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:4ZMrobQYDlLq2wMYK4806QBJ98k=,iv:Id8nWMM2m+1d4a1AHS+PcoHeM0TurVOLhnQBp5JBro0=,tag:AHRVf6N8O3yNfvjWZhpeEw==,type:str]
    clientSecret: ENC[AES256_GCM,data:BQ+lsGD+1FCwaRwpZ6kanaEflrVVtue6sy4ckGwM8A8AtggjXm9kPw==,iv:tWq4aFhrSOYpyFP20wvOmqsF1qVlVaK4nKl+E35VbIM=,tag:gYUQLLlT8Jf2/IVrH/AHyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbGN2S0YxV3BKZEw3RDNG
            WElRTGxJM1ltSTB5MGJPeCtvY3hZUXFKWFFNCm9YeVVzMFlhT3pSMURJSHpBYi9Y
            bVJQaUNWeFhSTnd1TVMySGZDNy82eFEKLS0tIDZRd0o2KzB4N1V1QmpSK2h5NE9h
            ZkVSSEpMQWx4WHlTRDFLZ3JEQi9hNjgKn0s7UlhC6l/zxiX3XLbdwoX3Nmq5JzAe
            PcBT6n3BAgn5Vlb7tOS8FDH2t+eTc34i2fMO2bMaImx0JF/1/S+40w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-07-21T12:24:05Z"
    mac: ENC[AES256_GCM,data:ruK7Olk+xSOLY80+6OfInI3Zag2raDW1dQoG0Yxmt/PzubSNxkcDjVJKOp5oxex5ZWlHearQReXPtweDQ/vinUS7C2LNfKpRak+XDQpUJOYGjk4Y532oJwvbFRzt0o6tnA2kPxdxsyhpNND2fSWktAggY1roTdvsa4mTWJ/8BR8=,iv:yzCspQzny2SCwcCKoGNARDNky8fOtPpPBBVxzXxBT+E=,tag:+ZZmIJkMXLMW2SckQ1K5Rg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
