apiVersion: ENC[AES256_GCM,data:vnk=,iv:FxRe09Hayx/LvGtcvvOMt8fik51geI+9CqBRQQI987g=,tag:+gAS30c/nE5QIFhTF61tQQ==,type:str]
kind: ENC[AES256_GCM,data:2psLMySm,iv:++y2tSYZ5ZCUg8uz6FDRgtVW2/VBAqo33vnUSl6w5DE=,tag:LlSHOFMRqF/Bc0zaLiRktA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VP20205HmLxwwgS6lotBg/H/7VcYZ2yDKVGeKA==,iv:YnDFc+AUmNn6FG3y5gO5p3eJORWozg3l6ZoCPWz89hc=,tag:ZgY1iIe39JVkOGJwGdnJ2Q==,type:str]
    namespace: ENC[AES256_GCM,data:A3jwUa/priOBotwQOfcc,iv:JXaO3fCaX+PjrI/n/LzODLHAcX8zl5B1L19o3Niw29I=,tag:0tje6dS0NicdoFoCFlK/QA==,type:str]
type: ENC[AES256_GCM,data:MKYEHcku,iv:Abcy0mIsJFyfpYXu95AhILAhLQ5KYEm1sZjCOR40RIE=,tag:tbts2xA/d1yxrHYiCrroqw==,type:str]
stringData:
    provider: ENC[AES256_GCM,data:StQV3nHV,iv:LBI1CB5HyG4t+oF6a2Ov5dr9UQ7g+k4f3VksvCXk/bA=,tag:ZpmMYro+rcoZqotBuUbEqQ==,type:str]
    clientId: ENC[AES256_GCM,data:7NMPbs08ed58ZYN4gQJM3X7uVYE=,iv:isLimvP6B1cgHVNYyf688h7eT0QTy4ZK7WyTk2+dTq8=,tag:yAjB3n8Bt6uLnSQWTyKMFg==,type:str]
    clientSecret: ENC[AES256_GCM,data:yAqYwatCjmuwuCvT92vgCXqLN9b3H1zCGK24rvROfCfS723As36avA==,iv:b8EWPjewm7NgpP5QBaVpQ70/NvTQRNDm3OHBM0Pxffw=,tag:+BilI6gJRgoMZUHp7p2QJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbDVoU0c2UVBRUFhub3BZ
            Yi9ic1dIUmx1WVRtODNjNkY1VExKWDhKRmxJCitSclZvUEpseFVIb0YwZXdpbVI1
            UVgvZ3NTcW5qUXREZUNHMUVvV0J1OVkKLS0tIHBwV1Nna0xaczNSSU4wcnNtNTI2
            OE1wN3hoSzMzSSszWXRSV29neUlIN0kK6W4PAHe9hK6EibQP3wWigJlucoAXjTEh
            iDqEgT9zFX+ia3r4DqLw4T7C7Jh/NMDNTSjyAOZsjCau+aewcQ8ZUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-07-21T12:10:11Z"
    mac: ENC[AES256_GCM,data:tVfKG9TAQkRP+eH/oD+kfFIDEE8wT4lB5hCzhxaYEJWZavkCqPUF76929+g/2He6WGPpLdzIt0MQJjqFaDgfi+259f2+hxnvE7979B8WCQFO2qEU9UWtBv4B8umqOED1u0zY+mwj95bX/bV+v80WOUTzzW5VQSRj4PSnWpqtSYg=,iv:Nk2DlDh0h39BTKlyBOwWRb3Pg9DPKP/7E5RfcrPJLbo=,tag:7JvCiJ6bwaw9QwdDNTCu7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
