apiVersion: ENC[AES256_GCM,data:yaQ=,iv:UdW/GnDHOiPk6VWZvbIzKBqdTFoY32RUXEhDyfeQCLw=,tag:bna4kTYNmiLGF6PnS4Pajg==,type:str]
kind: ENC[AES256_GCM,data:FuXCy+iX,iv:Za6DXzEbhrAK7LOUMBw02vagvnCAtEGpkM4mzKBQM4Y=,tag:z0U0VncV3O3EroPOSvHvAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eSeTSXLDOYDDWtLtcZcxVE1mcoljc/koH8ICrRGDpQ==,iv:xnNw1TBJ3/42wYYrwaL1eK+iuHPlGBj9kZOjT+Hvb0Q=,tag:DxKdB0NVRJJKXU4Kx7ZRlw==,type:str]
    namespace: ENC[AES256_GCM,data:Q3M5OXunn81GWoc6mG+h,iv:UmN4/cweVXBVxh3a4IGBrusB4D8qsbxjbqLjBYyy11A=,tag:eGvooJQmkiQ+LNKE2rAGGg==,type:str]
type: ENC[AES256_GCM,data:orUTIZ78,iv:NrnBWBC4kASZFl04GZzQpB7SysC5LnZnBkYQxdqsuK0=,tag:q+fJrMN8oJn4LBN15kuTyg==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:prLVdgmDQctTfNPFSd6KlrbqllzcL5hnf9gc9O085cGSqTM=,iv:pIPSMZuhX9TUyTICPM7lEf+2bu91x+Zd/fzItazqLTc=,tag:T9dsTtJ2qOvT8mRmaERDuw==,type:str]
    client-secret: ENC[AES256_GCM,data:sXklVOH/be/iy/OF7LGncHvtcyM30kOcLIRL8O7233WjFu4=,iv:XktzDffa3q1RD/AmEFAVpJ4EJMUROSfqyV14MzVSXZ0=,tag:UIxFsNbxk4v7Za2IKdlWUg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:azg6GzjeWM07Lj46lOIp+QNrpkEJwIbgYKq+A6h4HcY=,iv:Ys/oGlmFPSDbf2RiswcVuhWC5gEwdM8R+0S/gCakxYo=,tag:silekvmFUvLHmeHYi6ZeyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ1RDbEdWTm4vbHEwL2tn
            ZUNoTFVQYVJaYWFvM3NpRTF5b25sUE5xbFdvClhZSXoxeU5iU1pGUGJDOCtaK3Av
            WHc4MEt3VHFxYm5LR1JkekJETno0WVUKLS0tIG52bUZRbWlLNFZhZTNkdzM0Zzhq
            S3Z4ZVcrd3dYRTA0ZEZKUk5keEU3STgKXmeBNMAeDD7dxDFGMlZk05sJjon8in/7
            Goxc9vkH7u0AfRDmTKjZXMDNBltRrhk3ljLW47xtapvAoIEKHXbiZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-09-14T18:19:05Z"
    mac: ENC[AES256_GCM,data:v978x+DtG1Tqt5AvZ1qrHaDi7dG5FAyRZ0JaQ3XPIMPy3sQshNSsBWnVdvMGcedpawpWPqlLRojvyVZikBAeEzovNjg+RwpwkPElY9cG+tc6ubGVdi3//aySln6drFic6M2DvycJ79MLJx6gZK/3WDQC8yFGbUqQTqiglkNNjQ0=,iv:Xy0Cd/IUMDARW+WiMMhjruiYJCPHbmgUqY2yab6NYic=,tag:xHNTFhSfkfFNdp6NVZbIig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
