# SOPS Configuration File
# This file defines encryption rules for SOPS.
# To generate an age key: age-keygen -o key.txt
# To encrypt your secrets file: sops -e -i gitops/apps/taskflow/taskflow-secrets.yaml

creation_rules:
  - path_regex: .*-secrets\.yaml$
    age: "age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22"
