apiVersion: ENC[AES256_GCM,data:zdc=,iv:MmdlwYeIgTkclDzrboy8jAOHzDsNTTJ+HzMZ9iaL+5o=,tag:NjsKHZPc/JRHY6J0HtWFnQ==,type:str]
kind: ENC[AES256_GCM,data:urHFKSRr,iv:Jfrh3mFtDtlkfUGYYYx96q8aZKYdik6UIP6TaiFWh7g=,tag:RqH+sc8obNAiXFpkOYdI2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8ZxucLUPo/drzAqAla/6yMTI,iv:pqI6OEpLYLulc9yqlbD0h+DzALNf5U7obF0ALAOi8bs=,tag:kzcji/k7hScZPX9RMkrGrA==,type:str]
    namespace: ENC[AES256_GCM,data:0lQ7cLgTyHxdR/8=,iv:2H6opXwwAP2LDc8pg91Avr9swJDDKHj87Vzx2TiWEoY=,tag:KMsH7IPM3pBfjntEkzRyUQ==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:nkHw10A3+tVGNEiSk/RJ8FfamHe55PzMIp8EkTK2WyZmshGAT542VQA6PzOpgFxnmYi4G8/URr75Z/QSNFODb4eNSivyLK2kzOQer9ZK3aOThBrpJ+QruzXsFHqAKn0LCoWXNtNwlqokXHIikPSNGp7Eh4/mWVsr3lLmIB/Frm8sAXy93SYSUoz2hstFM8+K+geIqf7E7TqYsCI1dT/u5xgvJWt9+kwyXKZR5fj4wwLnXwabHmJFGQ==,iv:GASHAKajZgspRnEEB5ThSI7/buNVQXqJAVNNhoZtcgQ=,tag:6XWSWfirzgMGPivb+tR5OA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc2dBK2xxVUxxTm02Z2Ev
            a2R2Ykt3aTcyNHkwZ29sVzBTUVV3aDNmbEdjCitjVUEwcnVKT0xxSTJrOTQya2RQ
            SkxlRlVBazNnU0lPelBmaTlTZE9JSEUKLS0tIHZwbVVWRXFJVWs1SUVzdE5XU05L
            RWdEZnlNS2drOFhZL0lLNEZDWEZuNmsKscskRKiWv0H8FxlIHphhzeLrbLHwdEC5
            EgV1dPtY5LdYWU/R5kJJRkOyCTaFVJT+pGxQFcFOUFiBavFXP/2CrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-07-10T16:35:09Z"
    mac: ENC[AES256_GCM,data:ht2QDhAHjrv4JvjG8HvCA8n3etvohId3WQFrziXqTdj0uiPeRlNg8fzf9acECJvuhp6V4bxcP6pXmd9zx9pCkxx8xzPIz7dIORALvrGAZWq0keOAtS/Ps9D0slcq74hkhs0Qk2r4ZokKlOXAR559j8oEapm2ac2gC3+n1hlPcDM=,iv:aXdimFBA0FkdefxbtFxR7keKHSq0qNS/kuzZT/0Bvjo=,tag:g6ZzcgliWaHKCp85oaMnDw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
