apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infra-controllers.yaml
  - infra-configs.yaml
  - image-automation.yaml
  - taskflow.yaml
  - monitoring.yaml
  - monitoring-logging.yaml
  - monitoring-app.yaml
  - kyverno-policies.yaml
  - policy-reporter.yaml
  - trivy-operator.yaml
  - hubble-ui.yaml
  - renovate.yaml
