apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-job
  namespace: flux-system
spec:
  dependsOn:
    - name: renovate
  interval: 1h
  retryInterval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/controllers/renovate/job
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
