apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alloy-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: taskflow-observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 1Gi
