apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 30m
  chart:
    spec:
      chart: trivy-operator
      version: 0.34.0 # using a recent stable version
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy-system
      interval: 12h
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    trivy:
      ignoreUnfixed: false
      storageClassEnabled: true
      storageClassName: proxmox-csi
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
    scanJob:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
    operator:
      vulnerabilityScannerEnabled: true
      sbomGenerationEnabled: true
      configAuditScannerEnabled: true
      configAuditScannerScanOnlyCurrentRevisions: true
      rbacAssessmentScannerEnabled: true
      infraAssessmentScannerEnabled: true
      exposedSecretScannerEnabled: true
      clusterComplianceEnabled: true
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      scanJobTimeout: 5m
      builtInTrivyServer: true
      scanJobsConcurrentLimit: 1
      concurrentScanJobsLimit: 1
      scanNodeCollectorLimit: 1
    compliance:
      failEntriesLimit: 10
      reportType: all
      cron: "0 */6 * * *"
      specs:
        - k8s-nsa-1.0
        - k8s-cis-1.23
        - k8s-pss-baseline-0.1
        - k8s-pss-restricted-0.1
    trivyOperator:
      reportRecordFailedChecksOnly: true
    targetNamespaces: ""
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
