apiVersion: v1
kind: Secret
metadata:
    name: hubble-ui-github-oauth
    namespace: hubble-ui
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:Q6JMV13AyXPbTrsM5IeKc2qi9xs=,iv:ZK5sTcrxte4Dk1e81/Pdv+QpwuXRaZyROSIOpQUoeF4=,tag:qB3mJuEA+O1Op79ZoeQIRw==,type:str]
    client-secret: ENC[AES256_GCM,data:2maOEiUUNB9agX/wS5RcH77Vsf+UhD6YXgInB3VGZpErYiAQX1AJ4w==,iv:JSkWWITRngSxw+a+CCp5aso5RLO9U9ZKi7IGb7+6QPw=,tag:wAPpoJh2mMpNZm0lSR1kfw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:jdqQCjpaIj+2I8W6ZQf7eYvojGD4iykejgcyK+z3vKge765vjS/RcM6mNLA=,iv:QbKehv+2JWbKn/KEIv7fuHU8RHD5QsYj/F9D5+Ens3g=,tag:t8KmwC6n5c1DYia8i2tqMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MkViMkVDZlpJYmlrOTUy
            Zm1KZ0l6UHFTczRFR0MxVS9DTThrMng2NlFBClZPS3pYcnNXeUhoL2FkZEh1S2xG
            clNwNjdSa1NTZ0g2dmo2MHoweTJZT2sKLS0tIDNhTGR1VnpYc1QvcVU4dFZXRHU4
            SDRZejAwb2JyMHhXNEJzMTd2RUJSd0UKnSGNbO/XEaZdEiXXbJuivO1irp6uCmIy
            1j3/Nst98+MvRpMShjRjAOSJtRKl9Zcb/GQ5kT1l8kmoNWF6xmnwcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T11:19:58Z"
    mac: ENC[AES256_GCM,data:y8T8YNWlUjw+rTWeFiODLPOGQZQ5GcefzWu3qG08Tat86RMXP12I/+A7HkqsqlU8JL/mSB3HGmojMTmNe1lEcIRvqIO7qhjvuCVXx3oEiuTBjm/PtOnS+r5g7rbYsCWTeuwZZCDBV+VAbWea/8lODoMY6twQqlNNhDmWQP37CWI=,iv:l+Y0X60FrqA7yNQq0Jm1PVX5wVBGYbMSYDQVKPjk7Kw=,tag:HCyN73rxTIrWcykdTTC9fA==,type:str]
    version: 3.13.3
