apiVersion: v1
kind: Secret
metadata:
    name: hubble-ui-github-oauth
    namespace: hubble-ui
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:rTVz2ZSHRVp/9XilYtjy3RJAP88=,iv:8kAVUvpHMw7/TafP/YZrGzlICL7LBKMhggT1QGC7uRM=,tag:4OJziTy5f3OZ8EstXX0PdA==,type:str]
    clientSecret: ENC[AES256_GCM,data:5HPMcL9ychYZz3arTtAMPuwd1C/wxHlGA1PPAKbaHelWrMMBALhrVw==,iv:T4HUz7nU20R2YgwAQfXWwBNvkhhIs3YSVmnGVxAgEaY=,tag:HNf4X5q+4v4Bzz5O77to8Q==,type:str]
    cookieSecret: ENC[AES256_GCM,data:55L8iMQ0klmkxuAHyNhXhCD+kvrjdOJE8G5hTgQ5+LFzwJskpBHnHHBSnQ==,iv:Ti0vBw0IbHxUVE4348PN4225a+p6Vu4ZvvkNKLdjL6o=,tag:z33t02lQiDgimPKl07hGTA==,type:str]
    client-id: ENC[AES256_GCM,data:4v6ZxS5Pmbt9MVqfqp/ALd3GJBE=,iv:84sNqv8SmAk4pn9+FdKCns7MiZ5V2kPVXy/UG1H53yk=,tag:9jf4eIuvyK0Hc4QSJhlsHA==,type:str]
    client-secret: ENC[AES256_GCM,data:eILstBiIH0wRHiEllmRPIqGPSdJYK+XmR5FvwQeuO288KdY8vjaUFQ==,iv:6hZfaDUfAtfJ0ymRPbwFq9+bc/voaSaWMZchesPbwj0=,tag:7sG+yNni3ISz4ymR04IJcw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:RI5I8o3HDDW8Z2I2PZSPmw7Mxu4Ppbo5SFeSu7JZxwCb0U0Ob0YKJ2zktw==,iv:wGPu10EkW5e13KBQuyDbVt/WmCaYggJpiREwDyD5IQU=,tag:NTUghrAk+Y/MzfxRVeLGiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTHgzd3Q5d2JsZ25RZXBU
            OWltUmtLdTNhTDZPSDd2WVkwVnVKUjdZTEhzCmYzSlV2NGIrbzEra2VIMW5pOTI1
            Y2NPUnIzaUl6RnJqaTJKcmVxbTlNSk0KLS0tIHdFQm5QSllBZ1RoYlI5TGNWMFB6
            R2JXV1BYRmkyNFRLMFVSNElxTE1WdVEK3NhsEaWxrgiP9yzts6HbpDcspeLdvHsk
            0cfbm8Vh7GZNYDNMmxJ7Y0WrtAU7I/+tbqA3YDHt1zRiDnr7ppmGMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T11:15:54Z"
    mac: ENC[AES256_GCM,data:DCqnnoHizIpcjTHjYQpql3Bt99yDZ6Cw9SNVXxbg8xOcDaqLlu/L9aHyvD0UkseTkeV3ceN4SSV2eT0fDw4qREL497piH1kP3Z3aPfTBTaWhoWDTiFLUroKxWBfSc/XmpNyAd5RtT80mTwWzZbhdhgef7MFiE744Mr5JIdy+2rQ=,iv:rJDoUIX+kDQknqcYihhLoq8SUrRJ6sVUPXek2N6GEDs=,tag:tBqiFmoN9v1QbX9H2qvv+w==,type:str]
    version: 3.13.3
