apiVersion: v1
kind: Secret
metadata:
    name: hubble-ui-github-oauth
    namespace: hubble-ui
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:3r3jr6tdt3sMKSywz6jZ1Urd+kg=,iv:r43MmY/+Jho0GAAYKBrigCK/BdHr8caGMorwMnjyciE=,tag:Kj0dks0w3Gh1r2E6mNH2uA==,type:str]
    clientSecret: ENC[AES256_GCM,data:CPPRIaXrpTHBKow3XR2ogKct+tcwalLjV5iV7Gquv+RTW7QwzkxMSw==,iv:dP8p8QbnkFYfroKk7X1GdUKOHvWEsoxVHgJLpW/HxZ4=,tag:XcCuAwNagxHJpJYhL+7tcg==,type:str]
    cookieSecret: ENC[AES256_GCM,data:1hWUOXkTIvDWzPgTbO0eFQyjBNpLhh45lyNnD6pr7c9U7OgZaMiyrbR7fQ==,iv:V1qfYfrbPbEomtnFpk/zskDujR/tcK378iIDi0W8gAo=,tag:ZHJmuv76cn6GXGT5qXgTvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MnF5K3RSYU9HQ2dxcGlH
            OEtQK1hPSTB6RDVjRFFGZ3NsOTFZRHRXZlNRCmpUcnpsREhFV2F2TjVTWlhQZ1dZ
            ZGJpN1lwbFI2Y1VHbE1zckNRbmZJa28KLS0tIEhZWFlSTktsdEtKYUF2V25pcTF1
            ZnJKaHFrYSt4YVBlb3c1VVBaOHpUWlUKTbjUarBb39cEuV6FkpzvRewMrmWykcjW
            XT8o9nVsAPnN3L8bHHoaMfZTSYBBnbJbFvnMozRaVQo83D1jeVUvRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T10:24:41Z"
    mac: ENC[AES256_GCM,data:UxtCxaHw44jbwi+cru7KOxZSRIUeyIb12SHpCc9lU1//6/Ive1qKYy4zNBfcihRJCnMotB6nGWotDusoaPa8aziTQjz9N3hIXtjVSgfKevgjw0n4X52+NppzWL/+/LFWW+jzB0plsRbN/mY4LCMjmBKb8F+Y2EXf8IXpm9qI+uo=,iv:SIaIQsFFWPXMUo0jXpi1fcxuPHSiDMEnrc3rtKDV/tg=,tag:z7342jys2+mmdYiOzK4tPA==,type:str]
    version: 3.13.3
