apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    # Exempt Kyverno's own pods from any present/future Pod Security Admission policies.
    pod-security.kubernetes.io/enforce: privileged
