apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taskflow-jokelab-cert
  namespace: taskflow
spec:
  secretName: taskflow-tls-secret
  dnsNames:
    - "jokelab.dev"
    - "www.jokelab.dev"
    - "grafana.jokelab.dev"
  issuerRef:
    name: letsencrypt-http01-production
    kind: ClusterIssuer
