apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: taskflow
  labels:
    app: cloudflare-ddns
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/part-of: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: favonia/cloudflare-ddns:1.17.0
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CLOUDFLARE_API_TOKEN
            - name: DOMAINS
              value: "jokelab.dev,www.jokelab.dev,grafana.jokelab.dev,kyverno.jokelab.dev,hubble.jokelab.dev"
            - name: PROXIED
              value: "true"
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
