apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - taskflow-secrets.yaml
  - backend.yaml
  - frontend.yaml
  - jaeger.yaml
  - network-policy.yaml
  - postgres-db.yaml
  - postgres-pvc.yaml
  - redis.yaml
  - postgres-exporter.yaml
  - redis-exporter.yaml
  - gateway.yaml
  - httproute.yaml

