apiVersion: ENC[AES256_GCM,data:dTY=,iv:pjDDpqBI6ulUaiursZIIBsLSxz0XAHm1290SJDEfdnI=,tag:xBR6DGYaEHMO4mLdbFaopA==,type:str]
kind: ENC[AES256_GCM,data:ZF8v+C0C,iv:l2Lo1gcjBC3O3O+dFA8dP6kdwbTD0sicoL3+wZ4YT+Y=,tag:BU30JmDKnNAYmBQMlnny5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mlLoFGuQsOo=,iv:qxUP9StY0/RgQGzJCFiHuUIJK9iKLx0hYSBHO6yW0kM=,tag:ocHZ199IGlvIxZ5DegWTiQ==,type:str]
    namespace: ENC[AES256_GCM,data:xC0vo2plx1AplYo=,iv:wrxzzq+sv624zOPW1z4Snn10osoLClNQ56As50o6xhY=,tag:MZzQu11ZKaDMjK+rmQI4bQ==,type:str]
type: ENC[AES256_GCM,data:aKAwESVt,iv:GXp4TlXW3Td5JIoXivH4oWdAVGE3wVMvS5SatFbH54I=,tag:x2MCL6CQvpL77LYhJgnEsQ==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:5FPz4vlOnHZqmVqm55lpRXhCzAku9FPPZL1kEtr0N/8esyHsKFfC5yKgiZEPh/znZGQzTNSkRuiH2/y5utM8MTEm69iilBWpsdOmeHIAuktperZaUFZ+QRLwVbPqFoTdy4YA7D8hTc14bqdf4XCX0KW8QIqTh5jeZk2LVqC4qqqQKogwDCxfwLqlNM8jVOljcQv89TsLce0MvdAzum5Qt23zTUQ57jnduc1v1Gkf42dFbZN7CAFbdqC+N+Pa,iv:JqwrVEScP+Do7i9XzuwtTpoMMcfgoRIILml0f0dwuPg=,tag:hXTZZP7Xkh6/shZcY6CTJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSnBmVDFhalNqa1FRNTZ6
            U09HUGJ2dlFWYjhPUnBpaXBQR1J4TWg0QWt3CnJaMkFVeEd4RHBRWDhYeFQzdTgz
            bEx4UG1rMnpScjhoN3NrYVpPajJubDQKLS0tIE82eU5wUE11T3dxQ0FzMnFVMWJ0
            aDZQejdFbzUxWUw4T3RJUWJrdTFnS0EKk1+LnAFqmjbzqIQ7VW3GHRZSE0sn690k
            +CTkwD+OYYR3AsKmjCrdrUljb+XXpMaDWu0w4EH3Adx0YgyzUb0L1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tnw8z266962s0guenumuyqht55kt68grrx204wsle8u8p8ph9vscxnm22
    lastmodified: "2026-07-10T07:09:52Z"
    mac: ENC[AES256_GCM,data:DvjSf1DrWLAUoIZXjYomCMIpHUqVYOGVZAkPvtGCjAYo/pKhw0UqrZ+KegLxv2Td2xhvj/LjAhlWi5TCpyc2wtSTO/K+Mt9ikwjgrXz92hURDLHBEYfinbkeqToAnHX+dKbQMbdkyEQfHjUtBduI7ZvrfJyAY+AbqpCpc5O0060=,iv:uyRa6s0+GYkpVUAptc/xpXdIKkxtDZ/c/4waecjHbEY=,tag:8YMXxdCZ/vQYXlkTn9OBPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
