apiVersion: v1
kind: Namespace
metadata:
  name: abuseipdb
  labels:
    app.kubernetes.io/name: abuseipdb-sync
    app.kubernetes.io/component: ip-reputation-sync
    app.kubernetes.io/part-of: infrastructure
